### ISSUE TITLE
Feature: Desktop Notification Time Increase

### ISSUE THREAD

**Issue by Glacier150** [sergeant-savage/chatter#13]
Consider increasing the time a desktop notification appears on screen. Currently it is too short to read any decently long message.

**Comment by ItsCbass** [comment]
Honestly, hard agree on this. Messages don't last long enough. Possible implementation could be??
```js
setTimeout(newNotification.close.bind(newNotification), 5000); // Whatever we think is good in milisec
```

Thoughts??

**Comment by sergeant-savage** [comment]
@ItsCbass Looks good to me. I think that 5000 should be enough. We may need to rework the notifications system though. It feels a bit clunky right now.
