### ISSUE TITLE
Deployment Situation

### ISSUE THREAD

**Issue by Glacier150** [sergeant-savage/chatter#20]
The deployment situation is unacceptable and we need to fix it. @sergeant-savage @Glacier150 @ItsCbass 
IDK what this means but I was told by the project lead to open this issue.

**Comment by ItsCbass** [comment]
Before we get on this going, I just wanna get my ideas in front of you guys first. We could set up a CI/CD pipeline which if we go this route, GitHub actions or Jenkins would prob be the best bet. Another idea would just constructing an automated build script that'll run all of the necessary commands without having to do all the goofy stuff.

**Comment by sergeant-savage** [comment]
@ItsCbass Shuttle does provide a customized GitHub action, so I think we can set that to target the main branch and we should be good. I'll try to see if I can set that up tomorrow morning.

**Comment by sergeant-savage** [comment]
Now that I think about it, we can simultaneously use this issue to take care of #22 simultaneously.
