### ISSUE TITLE
Chore: Upgrade shuttle deps

### ISSUE THREAD

**Issue by sergeant-savage** [sergeant-savage/chatter#22]
Shuttle has released an update to their deployer. Some items in `Cargo.toml` will need to be upgraded.

**Comment by sergeant-savage** [comment]
Currently does not build with under version `0.37.0`. Will keep updated.

**Comment by sergeant-savage** [comment]
The project currently doesn't build under Shuttle version `0.37.0`, but will build and run under version `0.36.0`. @ItsCbass @Glacier150 Can either of you confirm/reproduce this behavior?7

**Comment by ItsCbass** [comment]
Let me give it a shot, I'll keep you updated

**Comment by sergeant-savage** [comment]
Will try this again tomorrow. Shuttle has been behaving very weirdly lately.
