### ISSUE TITLE
Prevent Site Botting Through iframes

### ISSUE THREAD

**Issue by Glacier150** [sergeant-savage/chatter#28]
A user has recently proven that, through repeating iframes in a coding playground, they can bot the site and overflows the site. This also allows for DDoS attacks.

**Comment by Glacier150** [comment]
It looks like we can use the HTTP Content-Security-Policy (CSP) frame-ancestors and set this to none. We should use this over XFO to prevent iframes on Edge. This is also better than a JS alternative which can be disabled.

`Content-Security-Policy: frame-ancestors 'none';`

**Comment by sergeant-savage** [comment]
`<meta http-equiv="Content-Security-Policy" content="frame-ancestors 'none';">`
seems like it would work.

If you wouldn't mind quickly implementing it, that'd be much appreciated.

**Comment by sergeant-savage** [comment]
This is not completed, that was a misclick.
